### ISSUE TITLE
Disables linting in Atom

### ISSUE THREAD

**Issue by amyrlam** [healthsparq/atom-ember-syntax#2]
This packages disables eslint-ing in the Atom UI for me, any idea why? 

Using this package in conjunction with these packages:

https://atom.io/packages/linter
https://atom.io/packages/linter-ui-default
https://atom.io/packages/linter-eslint
https://atom.io/packages/linter-stylelint
https://atom.io/packages/linter-ember-template

Or, do you know of other Atom packages that enable syntax highlighting for inline .hbs templates (`layout: hbs` in a .js file)?

**Comment by DHedgecock** [comment]
Hello @amyrlam, not sure if this has changed or was never documented, but it looks like now you need to add the grammar id to the list of scopes that ESLint will validate against.

Grammar id is `source.js.extended`, add to the atom-eslint settings under 'List of scopes to run ESLint on'

![screen shot 2017-10-20 at 1 05 24 pm](https://user-images.githubusercontent.com/8461733/31839813-927f8082-b597-11e7-927c-ac5dc0610002.png)

Please close if this fixes your issue!

**Comment by amyrlam** [comment]
@DHedgecock I tried that with `linter-eslint` but it didn't work for me ... still seems like enabling this package turns off `linter-eslint` or `linter-ui-default`

Here's a gif of it:
![linting](https://user-images.githubusercontent.com/1372946/31956313-e6024da6-b89f-11e7-92da-08a0eb94ecc4.gif)

**Comment by amyrlam** [comment]
Heya, can the issue be reopened for visibility?
